// <auto-generated />
namespace Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _211 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_211));
        
        string IMigrationMetadata.Id
        {
            get { return "201812262033182_2.1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
